name: CI-CD Docker Trivy Pipeline

on:
  push:
    branches:
      - trivy

env:
  IMAGE_NAME: ci-html
  IMAGE_TAG: latest
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.61.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.61.0_Linux-64bit.deb

      - name: Scan image
        run: trivy image $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG | tee trivy-report.txt

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt